on_click:
  - display.page.show: page3
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page2
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page3
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page2
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page3
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page2
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page3
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page2
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page3
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page2
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page3
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page2
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page3
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page2
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page3
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page2
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page3
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page2
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page3
  - component.update: my_display
  - delay: 0.6s
  - display.page.show: page1
  - component.update: my_display