automation: !include automations.yaml
camera: !include camera.yaml
cover: !include cover.yaml
default_config:
frontend: !include frontend.yaml
homeassistant:
  customize: !include customize.yaml
  auth_mfa_modules:
    - type: totp
home_connect_alt: !include home_connect_alt.yaml
http: !include http.yaml
influxdb: !include influxdb.yaml
ios: !include ios.yaml
light: !include light.yaml
logger: !include logger.yaml
monitor_docker: !include monitor_docker.yaml
recorder:
  db_url: !secret mariadb_url
media_player: !include media_player.yaml
mqtt: !include mqtt.yaml
nordpool:
panel_iframe: !include panel_iframe.yaml
powercalc: !include powercalc.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
template: !include template.yaml
tts: !include tts.yaml
utility_meter: !include utility_meter.yaml
zha:
  zigpy_config:
    network:
      channel: 11
