- platform: template
  covers:
    garage_door:
      device_class: garage
      friendly_name: "Garage Door"
      value_template: >-
        {% if is_state('binary_sensor.garage_door_sensor_iaszone', 'off') %}
          Closed
        {% elif is_state('binary_sensor.garage_door_sensor_iaszone', 'on') %}
          Open
        {% else %}
          Unknown
        {% endif %}
      open_cover:
        service: switch.toggle
        target:
          entity_id: switch.garage_door_opener_relay
      close_cover:
        service: switch.toggle
        target:
          entity_id: switch.garage_door_opener_relay
      icon_template: >-
        {% if is_state('binary_sensor.garage_door_contact', 'off') %}
          mdi:garage
        {% else %}
          mdi:garage-open
        {% endif %}