substitutions:
  devicename: bt_proxy
  upper_devicename: BT Proxy
  hardware: TTGO T-display (ESP32)

esphome:
  name: "$devicename"
  comment: "$upper_devicename - $hardware"

esp32:
  board: esp32dev
  framework:
    type: arduino

bluetooth_proxy:
esp32_ble_tracker:

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

ota:
  password: !secret ota_password

logger:

api:
  password: !secret api_password
  reboot_timeout: 0s

time:
  - platform: homeassistant
    id: esptime