substitutions:
  devicename: garage_door_opener
  upper_devicename: Garage Door Opener
  hardware: Shelly 1

esphome:
  name: "$devicename"
  comment: "$upper_devicename - $hardware"
  platform: ESP8266
  board: esp01_1m

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

ota:
  password: !secret ota_password

logger:

api:

switch:
  - platform: gpio
    pin: GPIO4
    name: "$upper_devicename - Relay"
    id: relay