substitutions:
  devicename: kitchen_freezer
  upper_devicename: Kitchen Freezer
  hardware: Sonoff POW

esphome:
  name: "$devicename"
  comment: "$upper_devicename - $hardware"
  platform: ESP8266
  board: esp8285

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

logger:

api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    change_mode_every: 2
    update_interval: 10s

    power:
      id: power
      name: "$upper_devicename - Power"
      unit_of_measurement: W
      accuracy_decimals: 1
      filters:
        - calibrate_linear:
            - 4.1 -> 0.75
            - 9.3 -> 1.65
            - 16.5 -> 2.85
            - 87 -> 14.5
            - 938 -> 157
            - 1799 -> 303
            - 1816 -> 304.8
            - 6228 -> 1045
            - 9414 -> 1580
            - 10800 -> 1815
        - lambda: if (x < (2 + 1.14)) return 0; else return (x - 1.14);

  - platform: total_daily_energy
    name: "$upper_devicename - Consumption"
    power_id: power
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  - platform: gpio
    name: "$upper_devicename - Button"
    pin:
      number: GPIO3
      inverted: true
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    id: relay
    internal: true
    name: "$upper_devicename - Switch"
    pin: GPIO14
    restore_mode: ALWAYS_ON
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO1
      inverted: true

light:
  - platform: monochromatic
    output: state_led
    internal: true
    id: led

status_led:
  pin:
    number: GPIO13
    inverted: true