substitutions:
  devicename: kitchen_countertop_light
  upper_devicename: Kitchen Countertop Light
  hardware: Sonoff Basic R2

esphome:
  name: "kitchen-countertop-light"
  comment: "$upper_devicename - $hardware"
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

logger:

api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: gpio
    id: button
    internal: true
    name: "$upper_devicename - Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.toggle: "$devicename"

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO13
      inverted: true
  - platform: gpio
    pin: GPIO12
    id: relay

light:
  - platform: monochromatic
    output: green_led
    id: led
  - platform: binary
    name: "$upper_devicename"
    output: relay
    id: "$devicename"