substitutions:
  devicename: sniffer
  upper_devicename: Sniffer
  hardware: TTGO T-display (ESP32)

esphome:
  name: "$devicename"
  comment: "$upper_devicename - $hardware"

  includes:
    - acurite.h
esp32:
  framework:
    type: arduino
  board: esp-wrover-kit
wifi:
  reboot_timeout: 10min
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

ota:
  password: !secret ota_password

logger:

api:
  reboot_timeout: 0s

time:
  - platform: homeassistant
    id: esptime

remote_receiver:
  id: receiver
  pin: 
    number: 33
    inverted: true
  idle: 6ms
  filter: 200us
  tolerance: 35%

custom_component:
  lambda: |-
    return {new Acurite()};

sensor:
binary_sensor:
text_sensor: